services:
  n8n:
    image: n8n-custom
    ports:
      - "5678:5678"
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=yourname
      - N8N_BASIC_AUTH_PASSWORD=yourpassword
    volumes:
      - /d/DockerData/n8n-data:/home/node/.n8n
      - /d/DockerData/scripts:/data/scripts
    